object AppStrings {
    // General
    const val APP_NAME = "Penn Mobile"
    const val MAIN_TITLE = "Penn Mobile"
    const val ACTION_SETTINGS = "Settings"
    const val SEARCH_TITLE = "Search"
    const val REGISTRAR = "Courses"
    const val DINING = "Dining"
    const val GSR = "GSR Booking"
    const val NEWS = "News"
    const val LAUNDRY = "Laundry"
    const val SUPPORT = "Campus Help"
    const val ABOUT = "About"
    const val FITNESS = "Fitness"
    const val LABS_ICON = "Penn Labs"
    const val NO_RESULTS = "No results found"
    const val ACTION_LICENSES = "Open Source Licenses"
    const val MORE = "More"

    // Contacts
    const val ADD_CONTACT = "Add contact"
    const val SAVE_CONTACTS = "Select Contacts to Save"
    const val ASK_CONTACTS_FAIL = "Access to your contacts is required to use this feature."

    // Home Screen
    const val HOME = "Home"

    // Floating Bottom Bar
    const val ACCESSIBILITY_DESCRIPTION = "Screen menu"
    const val ACCESSIBILITY_ITEM_DESCRIPTION = "%1\$s menu item"

    // Fitness
    const val FITNESS_ROOM_OPEN = "Open"
    const val FITNESS_ROOM_CLOSED = "Closed"

    // Dining
    const val DINING_HALL_OPEN = "Open"
    const val DINING_HALL_CLOSED = "Closed"
    const val DINING_HALL_BREAKFAST = "Breakfast"
    const val DINING_HALL_BRUNCH = "Brunch"
    const val DINING_HALL_LUNCH = "Lunch"
    const val DINING_HALL_DINNER = "Dinner"
    const val DINING_HALL_LATE_NIGHT = "Late Night"
    const val DINING_INFO = "Dining Hall Hours"
    const val MENU_ARG_NAME = "name"
    const val MENU_ARG_MEAL = "meal"
    const val MENU_ARG_STATIONS = "stations"
    const val SORT_BY_NAME = "Order by Name"
    const val SORT_BY_RESIDENTIAL = "Order by Residential Hall"
    const val SORT_BY_OPEN = "Order by Open Status"
    const val DINING_CLOSED = "Closed today"
    const val DINING_BALANCE = "Dining Balance"
    const val DINING_DOLLARS = "Dining Dollars"
    const val DINING_SWIPES = "Swipes"
    const val DINING_GUEST_SWIPES = "Guest Swipes"
    const val MONEY = "$"
    const val AVERAGE_DINING_DOLLARS_SPENT = "Average Dining Dollars Spent"
    const val PAST_WEEK = "this past week"
    const val DINING_DOLLARS_PREDICTIONS = "Dining Dollars Predictions"
    const val DINING_SWIPES_PREDICTIONS = "Swipes Predictions"
    const val CAMPUS_EXPRESS_TOKEN = "Campus Express Token"
    const val CAMPUS_TOKEN_EXPIRES_IN = "Campus Express Token Expires In"
    const val EXTRA_BALANCE = "Extra Balance"
    const val OUT_OF_DINING_DOLLARS = "Out of Dollars"
    const val OUT_OF_DINING_DOLLARS_MESSAGE = "You have no dining dollars left for this semester."
    const val OUT_OF_DINING_DOLLARS_PREDICTION_MESSAGE =
        "Based on your current balance and past behavior, we project you'll run out on this date."
    const val EXTRA_DINING_DOLLARS_MESSAGE =
        "Based on your past behavior, we project you'll end the semester with dining dollars to spare."
    const val OUT_OF_DINING_SWIPES = "Out of Swipes"
    const val OUT_OF_DINING_SWIPES_MESSAGE = "You have no swipes left for this semester."
    const val OUT_OF_DINING_SWIPES_PREDICTION_MESSAGE =
        "Based on your current balance and past behavior, we project you'll run out on this date."
    const val EXTRA_DINING_SWIPES_MESSAGE =
        "Based on your past behavior, we project you'll end the semester with swipes to spare."
    const val DINING_GRAPH_POINT = "Date Filler Text \n Swipes Filler Text"

    // LaundryRoom
    const val LAUNDRY_WASHER = "Washers"
    const val LAUNDRY_DRYER = "Dryers"
    const val LAUNDRY_SUMMARY = "Summary"
    const val LAUNDRY_AVAILABLE = "Available"
    const val LAUNDRY_AVAILABLEIN = "left"
    const val LAUNDRY_WASHER_TEXTVIEW = "Washer"
    const val LAUNDRY_DRYER_TEXTVIEW = "Dryer"
    const val LAUNDRY_NOTIFICATION_ALARM_INTENT = "From alarm"
    const val LAUNDRY_NOTIFICATION_SNACKBAR_ON = "Notification turned on for "
    const val LAUNDRY_NOTIFICATION_SNACKBAR_OFF = "Notification turned off for "
    const val LAUNDRY_SWITCH = "Activate switch for notification when complete"
    const val LAUNDRY_UNDO = "UNDO"
    const val LAUNDRY_HALL_NO = "hall_no"
    const val LAUNDRY_POSITION = "position"
    const val LAUNDRY_MACHINE_INTENT = "machines"
    const val LAUNDRY_HALL_ARG = "Laundry Hall"
    const val LAUNDRY_NOT_UPDATE = "not updating status"
    const val LAUNDRY_STATUS_UNAVAILABLE = "status unavailable"
    const val FAVORITE_TITLE = "Favorite"
    const val LAUNDRY_SETTINGS = "Laundry Settings"
    const val NOT_UPDATING_STATUS = ""
    const val LAUNDRY_RESET = "RESET"
    const val LAUNDRY_HELP_TEXT = "Please click the settings icon to choose laundry rooms"
    const val LAUNDRY_SETTINGS_HELP1 = "Please select up to 3 laundry rooms"
    const val LAUNDRY_SETTINGS_HELP2 = "Click RESET to reset your selections"
    const val LAUNDRY_MACHINES_AVAILABLE = "machines available"
    const val WASHER = "washer"
    const val DRYER = "dryer"
    const val OPEN = ""
    const val NOT_AVAILABLE = "not available"
    const val MIN_LEFT = "min left"
    const val NUM_ROOMS_SELECTED_PREF = "numRoomsSelected"
    const val NUM_ROOMS_PREF = "numRooms"
    const val LOCATION = "location"
    const val AVAILABLE = "available"
    const val S = "s"
    const val MACHINES = "machines"
    const val LAUNDRY_MACHINE_TYPE = "machineType"
    const val STATUS_OUT_OF_ORDER = "Out of order"
    const val STATUS_NOT_ONLINE = "Not online"
    const val STATUS_AVAILABLE = "Available"
    const val STATUS_READY_TO_START = "Ready to start"
    const val STATUS_END_OF_CYCLE = "End of cycle"
    const val LAUNDRY_ROOM_NAME = "roomName"
    const val LAUNDRY_MACHINE_ID = "id"
    const val OPEN_BROWSER = "Open in Browser"
    const val NEWS_SHARING = "Share link"

    // About
    const val LICENSES = "LICENSES"
    const val HI_WE_ARE_LABS =
        "Hi, we're Penn Labs: a team of student software engineers, product designers, and business developers."
    const val LABS_MISSION =
        "Penn Labs empowers others to make connections: connections to resources, connections to people, and connections to the greater Penn community.\n\n" +
                "Our ultimate goal is improving the Penn community. We aim to do so not only by creating high quality products, but also by giving back to the community with educational resources and technical support."
    const val LEARN_MORE = "LEARN MORE"
    const val FEEDBACK = "FEEDBACK"
    const val FEEDBACK_TXT = "Click below to give us feedback!"
    const val REQUEST_FEATURE = "REQUEST A FEATURE"
    const val OUR_TEAM = "Our Team"
    const val ALUMNI = "Alumni (2020-2023) "
    const val PENN_LABS_COPYRIGHT = "\u00A9 2023 Penn Labs"
    const val PREF_COURSES_TITLE = "Courses"
    const val PREF_RECITATIONS = "Show recitations"

    // Preferences
    const val PREF_RECITATIONS_SUMM = "Display recitations in search results"
    const val PREF_DINING_TITLE = "Dining"
    const val PREF_VEGETARIAN = "Show only vegetarian items"
    const val PREF_VEGETARIAN_SUMM = "Display only vegetarian food items in the dining menus"
    const val PREF_VEGAN = "Show only vegan items"
    const val PREF_VEGAN_SUMM = "Display only vegan food items in the dining menus"
    const val HOME_SCREEN_PREF = "home_screen_pref"

    // GSR
    const val SEARCH_GSRS = "Search GSRs"
    const val QUIT_BOOK = "<- Back"
    const val TO = "to"
    const val SEARCH_DATE = "Date"
    const val FIRST_NAME = "First name"
    const val LAST_NAME = "Last name"
    const val EMAIL_ADDRESS = "Email Address"
    const val SUBMIT = "Submit"
    const val ANY = "Any"
    const val DATE = "Date"
    const val HUNTSMAN_GSR_SESSIONID = "HuntsmanGSR_SessionID"
    const val TIME = "Time"
    const val DURATION = "Duration"
    const val GSR_LOCATION = "Location"
    const val NO_GSR_RESERVATIONS = "No upcoming GSR reservations"
    const val NO_GSR_ROOMS = "No GSRs available"
    const val SPRING_FLING = "Spring Fling"
    const val FLING_EVENT_TIME = "%1\$s - %2\$s"
    const val SPEC_SPRING_FLING_2019_RAFFLE = "SPEC Spring Fling 2019 Raffle"
    const val FIRST_OPEN_PREF = "first_open"

    // Spring Fling
    const val NO_HOME_ITEMS_MESSAGE =
        "No items selected, click on settings in the top right of the screen to change this"
    const val PENNKEY_LOGIN = "LOG IN WITH PENNKEY"
    const val GUEST_LOGIN = "CONTINUE AS GUEST"

    // Login
    const val LOGIN_SESSIONID = "loginSessionID"
    const val ACCESS_TOKEN = "accessToken"
    const val REFRESH_TOKEN = "refreshToken"
    const val EXPIRES_IN = "expiresIn"
    const val TOKEN_EXPIRES_AT = "tokenExpiresAt"
    const val PENN_USER = "pennUser"
    const val PENN_PASSWORD = "pennPassword"
    const val TITLE_ACTIVITY_LOGIN = "Sign in"
    const val PENNKEY = "pennkey"
    const val ACCOUNTID = "\"Account ID\""

    // Accounts
    const val PROMPT_PASSWORD = "Password"
    const val ACTION_SIGN_IN = "Sign in or register"
    const val ACTION_SIGN_IN_SHORT = "Sign in"
    const val WELCOME = "\"Welcome !\""
    const val INVALID_USERNAME = "Not a valid username"
    const val INVALID_PASSWORD = "Password must be >5 characters"
    const val LOGIN_FAILED = "\"Login failed\""
    const val GUEST_MODE = "\"Guest\""
    const val FLOATING_BOTTOM_BAR_HOME = "Home"
    const val FLOATING_BOTTOM_BAR_PCA = "PCA"
    const val FLOATING_BOTTOM_BAR_DINING = "Dining"
    const val FLOATING_BOTTOM_BAR_GSR_BOOKING = "GSR"
    const val FLOATING_BOTTOM_BAR_LAUNDRY = "Laundry"
    const val FLOATING_BOTTOM_BAR_MORE = "More"
    const val INITIALS = "Initials"
    const val INTERNET_ERROR = "Not Connected to the Internet"
    const val PENN_MOBILE = "Penn Mobile"
    const val CONTACTS = "Contacts"
    const val SAVE_SELECTION = "Click to save selection"
    const val LAUNDRY_ALARM_OFF = "Alarm Cancelled."

    // PCA
    const val PCA_DESCRIPTION = "Get alerted when a course opens up!"
    const val PCA_TITLE = "Penn Course Alert"
    const val PCA_COURSE = "Course"
    const val PCA_PHONE_NUMBER = "Phone Number"
    const val PCA_SUBMIT_BUTTON = "Alert Me!"
    const val PCA_NOTIFY_WHEN_CLOSED = "Notify when closed?"

    // Poll
    const val VOTE = "Vote"
    const val SORT_BY = "Sort By:"
    const val ROOM_NUMBER = "Room Number"
    const val POTTRUCK = "Pottruck"
    const val FITNESS_SUNDAY = "Sunday"
    const val FITNESS_MF = "Mon - Fri"
    const val FITNESS_SAT = "Saturday"
    const val FITNESS_CAPACITY = "Capacity"
    const val ROOM = "Room"
    const val APPWIDGET_TEXT = "EXAMPLE"
    const val ADD_WIDGET = "Add widget"
    const val APP_WIDGET_DESCRIPTION = "This is an app widget description"
    const val YOU_HAVE_NO_RESERVATIONS_OR_ARE_LOGGED_OUT =
        "You have no reservations or are logged out"
    const val LOGIN_BACKGROUND = "Login Background"
    const val PENN_MOBILE_ICON = "Penn Mobile Icon"
    const val CANCEL = "Cancel"
}
